# Generated by Django 2.0 on 2017-12-21 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('visage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('S', 'Submitted'), ('P', 'Processing'), ('E', 'Error'), ('J', 'Judged')],
                                   db_index=True, default='S', max_length=1, verbose_name='status'),
        ),
    ]
