# Generated by Django 2.0 on 2017-12-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('visage', '0002_auto_20171221_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='score',
        ),
        migrations.AddField(
            model_name='submission',
            name='error',
            field=models.FloatField(blank=True, db_index=True, null=True, verbose_name='error'),
        ),
    ]
