# Generated by Django 2.0 on 2018-02-01 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('visage', '0003_auto_20171223_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_final',
            field=models.BooleanField(default=False, verbose_name='is final'),
        ),
    ]
