# Generated by Django 2.0 on 2017-12-20 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='active',
            field=models.BooleanField(default=False, verbose_name='active'),
        ),
    ]
